/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;


public class Teladelogin extends javax.swing.JFrame {

    /**
     * Creates new form Teladelogin
     */
    public Teladelogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTFLOGIN = new javax.swing.JTextField();
        JPSSENHA = new javax.swing.JPasswordField();
        JBENTRAR = new javax.swing.JButton();
        JBSAIR = new javax.swing.JButton();
        tUser = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("TELA DE LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 36, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("LOGIN:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 83, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("SENHA:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        JTFLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFLOGINActionPerformed(evt);
            }
        });
        getContentPane().add(JTFLOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 83, 210, -1));
        getContentPane().add(JPSSENHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 130, 210, -1));

        JBENTRAR.setText("ACESSAR");
        JBENTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBENTRARActionPerformed(evt);
            }
        });
        getContentPane().add(JBENTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 247, -1, -1));

        JBSAIR.setText("SAIR");
        JBSAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSAIRActionPerformed(evt);
            }
        });
        getContentPane().add(JBSAIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 247, 82, -1));

        tUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PACIENTE", "ADMINISTRADOR", "SECRETÁRIA" }));
        getContentPane().add(tUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 187, 136, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("USUÁRIO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 187, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 232, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBENTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBENTRARActionPerformed
        
        if(JTFLOGIN.getText().toString().equals("") && JPSSENHA.getText().toString().equals("") && tUser.getSelectedItem().toString().equals("SECRETÁRIA")){
        
              JOptionPane.showMessageDialog(null,"Preencha os campos");
        }else if (JTFLOGIN.getText().toString().equals("admin") && JPSSENHA.getText().toString().equals("123456") && tUser.getSelectedItem().toString().equals("SECRETÁRIA")){
            Secretaria obj = new Secretaria();
            obj.setVisible(true);
            dispose();
        }else{
        JOptionPane.showMessageDialog(null,"Acesso negado");
        }
        
       /* if(JTFLOGIN.getText().toString().equals("") && JPSSENHA.getText().toString().equals("") && tUser.getSelectedItem().toString().equals("PACIENTE")){
        
              JOptionPane.showMessageDialog(null,"Preencha os campos");
        }else if (JTFLOGIN.getText().toString().equals("admin") && JPSSENHA.getText().toString().equals("123456") && tUser.getSelectedItem().toString().equals("PACIENTE")){
            Cmedico med = new Cmedico();
            med.setVisible(true);
            dispose();
        }else{
        JOptionPane.showMessageDialog(null,"Acesso negado");
        }

    } */
    }//GEN-LAST:event_JBENTRARActionPerformed

    private void JBSAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSAIRActionPerformed
       
    }//GEN-LAST:event_JBSAIRActionPerformed

    private void JTFLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFLOGINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFLOGINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teladelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teladelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teladelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teladelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teladelogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBENTRAR;
    private javax.swing.JButton JBSAIR;
    private javax.swing.JPasswordField JPSSENHA;
    private javax.swing.JTextField JTFLOGIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> tUser;
    // End of variables declaration//GEN-END:variables
}
